import { Router, type Request, type Response } from "express";
import { db } from "@workspace/db";
import { reportsTable, goalsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { groq } from "../lib/groq.js";
import { pushFilesToGitHub } from "../lib/github.js";
import { broadcast } from "../lib/websocket.js";

const router = Router();

router.get("/", async (req: Request, res: Response): Promise<void> => {
  try {
    const reports = await db.select().from(reportsTable).orderBy(reportsTable.createdAt);
    res.json(reports);
  } catch (err) {
    req.log.error({ err }, "Failed to list reports");
    res.status(500).json({ error: "Failed to list reports" });
  }
});

router.post("/generate", async (req: Request, res: Response): Promise<void> => {
  const { goalId, reportType } = req.body as { goalId?: number; reportType?: string };

  try {
    let contextText = "Generate a comprehensive executive intelligence report for HiveMind Nexus AI workforce platform.";
    if (goalId) {
      const [goal] = await db.select().from(goalsTable).where(eq(goalsTable.id, goalId));
      if (goal) contextText = `Generate an executive report for the business goal: "${goal.title}". Description: ${goal.description}`;
    }

    const type = reportType || "executive";
    const reportTypeLabels: Record<string, string> = {
      executive: "Executive Summary",
      financial: "Financial Intelligence Report",
      market: "Market Analysis Report",
      strategy: "Strategic Planning Report",
      performance: "Agent Performance Report",
    };
    const label = reportTypeLabels[type] || "Intelligence Report";

    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: `You are the CEO Agent of HiveMind Nexus generating a formal ${label}. Write in a professional, executive tone. Use markdown formatting with ## headers. Be specific with numbers and insights.`,
        },
        {
          role: "user",
          content: `${contextText}\n\nReport Type: ${label}\nDate: ${new Date().toISOString().split("T")[0]}\n\nGenerate a 400-600 word intelligence report with executive summary, key findings, strategic recommendations, and action items.`,
        },
      ],
      max_tokens: 900,
      temperature: 0.6,
    });

    const content = completion.choices[0]?.message?.content || "Report generation failed.";
    const title = `${label} — ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`;

    const [report] = await db
      .insert(reportsTable)
      .values({
        goalId: goalId || null,
        reportType: type,
        title,
        content,
        generatedBy: "CEO Agent",
      })
      .returning();

    broadcast("report_generated", report);

    // Auto-push the report to GitHub
    const safeName = title.replace(/[^a-z0-9]/gi, "_").substring(0, 60);
    const filePath = `generated-reports/${safeName}_${report.id}.md`;
    const fileContent = `# ${title}\n\n**Generated by:** ${report.generatedBy}  \n**Date:** ${new Date().toISOString()}  \n**Report Type:** ${type}  \n${goalId ? `**Goal ID:** ${goalId}  ` : ""}\n\n---\n\n${content}`;

    pushFilesToGitHub(
      [{ path: filePath, content: fileContent }],
      `📊 Auto-generated: ${title}`
    ).catch(() => {});

    res.status(201).json(report);
  } catch (err) {
    req.log.error({ err }, "Failed to generate report");
    res.status(500).json({ error: "Failed to generate report" });
  }
});

export default router;
