import { useState } from "react";
import { motion } from "framer-motion";
import { useListReports, useListGoals } from "@workspace/api-client-react";
import { FileText, Plus, Loader2, ChevronDown, ChevronUp } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { formatDistanceToNow } from "date-fns";
import { useQueryClient } from "@tanstack/react-query";

const REPORT_TYPES = [
  { value: "executive", label: "Executive Summary" },
  { value: "financial", label: "Financial Intelligence" },
  { value: "market", label: "Market Analysis" },
  { value: "strategy", label: "Strategic Planning" },
  { value: "performance", label: "Agent Performance" },
];

function ReportCard({ report }: { report: { id: number; title: string; content: string; generatedBy: string; reportType: string; createdAt: string } }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card className="glass-card border-white/10 hover:border-primary/30 transition-all duration-300" data-testid={`report-card-${report.id}`}>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-2">
          <CardTitle className="text-base font-semibold leading-tight">{report.title}</CardTitle>
          <div className="flex items-center gap-2 flex-shrink-0">
            <Badge variant="outline" className="text-xs border-chart-1/30 bg-chart-1/10 text-chart-1">{report.reportType}</Badge>
          </div>
        </div>
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span className="font-mono">Generated by {report.generatedBy}</span>
          <span className="font-mono">{formatDistanceToNow(new Date(report.createdAt), { addSuffix: true })}</span>
        </div>
      </CardHeader>
      <CardContent>
        <div className={`text-sm text-muted-foreground leading-relaxed ${expanded ? "" : "line-clamp-3"} whitespace-pre-wrap`}>
          {report.content}
        </div>
        <Button variant="ghost" size="sm" className="mt-3 gap-1 text-xs text-muted-foreground hover:text-foreground"
          onClick={() => setExpanded(!expanded)} data-testid={`button-expand-report-${report.id}`}>
          {expanded ? <><ChevronUp className="h-3 w-3" /> Collapse</> : <><ChevronDown className="h-3 w-3" /> Read More</>}
        </Button>
      </CardContent>
    </Card>
  );
}

export default function Reports() {
  const { data: reports, isLoading, refetch } = useListReports();
  const { data: goals } = useListGoals();
  const [open, setOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [selectedGoal, setSelectedGoal] = useState<string>("");
  const [selectedType, setSelectedType] = useState("executive");

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const body: Record<string, unknown> = { reportType: selectedType };
      if (selectedGoal) body.goalId = parseInt(selectedGoal);
      await fetch("/api/reports/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      await refetch();
      setOpen(false);
    } catch {
      // ignore
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Intelligence Reports</h1>
          <p className="text-muted-foreground mt-1">AI-generated executive reports and strategic intelligence.</p>
        </div>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2" data-testid="button-generate-report">
              <Plus className="h-4 w-4" /> Generate Report
            </Button>
          </DialogTrigger>
          <DialogContent className="bg-card border-border">
            <DialogHeader><DialogTitle>Generate Intelligence Report</DialogTitle></DialogHeader>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>Report Type</Label>
                <Select onValueChange={setSelectedType} defaultValue="executive">
                  <SelectTrigger data-testid="select-report-type"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {REPORT_TYPES.map(t => <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Business Goal (optional)</Label>
                <Select onValueChange={setSelectedGoal}>
                  <SelectTrigger data-testid="select-report-goal"><SelectValue placeholder="General report..." /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">General (no specific goal)</SelectItem>
                    {goals?.map(g => <SelectItem key={g.id} value={String(g.id)}>{g.title}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <Button className="w-full gap-2" disabled={generating} onClick={handleGenerate} data-testid="button-submit-report">
                {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
                {generating ? "AI is writing report..." : "Generate Report"}
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {isLoading ? (
        <div className="space-y-4">{[1,2,3].map(i => <div key={i} className="h-32 rounded-lg bg-muted animate-pulse" />)}</div>
      ) : reports?.length === 0 ? (
        <Card className="glass-card border-white/10">
          <CardContent className="py-20 text-center">
            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4 opacity-50" />
            <p className="text-muted-foreground">No reports generated yet. Generate your first intelligence report.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {[...(reports || [])].reverse().map((report, i) => (
            <motion.div key={report.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.07 }}>
              <ReportCard report={report} />
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
